### ISSUE TITLE
App crashes as soon I hit OK to select a directory. 

### ISSUE THREAD

**Issue by Fatcakes** [slowscript/warpinator-android#14]
I'm on android 8.1.0

**Comment by slowscript** [comment]
I have noticed this happens to multiple people but I couldn't reproduce it on any of my devices. Would you be able to provide a logcat?

**Comment by Fatcakes** [comment]
I'm pretty terrible at doing things like this in a timely manner. If you want you can emulate my current rom using bluestacks or something similar.

https://forum.xda-developers.com/t/rom-un-official-lineageos-15-1-for-nexus-6-shamu.3773143/

**Comment by slowscript** [comment]
I have just published a new release with many bugfixes. Please let me know if it fixed your problem.

**Comment by Fatcakes** [comment]
@slowscript Just got the update. Still crashes for me unfortunately.

**Comment by slowscript** [comment]
We now use a default directory when possible and even if the prompt shows it should no longer crash.
